export enum TaskEventType {
  TASK_CREATED = 'TASK_CREATED',
  TASK_UPDATED = 'TASK_UPDATED',
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  SEVERITY_CHANGED = 'SEVERITY_CHANGED',
  NAME_CHANGED = 'NAME_CHANGED',
  COMMENT_ADDED = 'COMMENT_ADDED',
  TASK_DELETED = 'TASK_DELETED',
  PROGRESS_CHANGED = 'PROGRESS_CHANGED',
  DATES_CHANGED = 'DATES_CHANGED',
}
