export enum TicketEventType {
  TICKET_CREATED = 'TICKET_CREATED',
  TICKET_UPDATED = 'TICKET_UPDATED',
  TICKET_ASSIGNED = 'TICKET_ASSIGNED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  SEVERITY_CHANGED = 'SEVERITY_CHANGED',
  QUEUE_CHANGED = 'QUEUE_CHANGED',
  NAME_CHANGED = 'NAME_CHANGED',
  COMMENT_ADDED = 'COMMENT_ADDED',
  TICKET_DELETED = 'TICKET_DELETED',
}
