import { ApiProperty } from '@nestjs/swagger';
import {
  IsNotEmpty,
  IsOptional,
  IsNumber,
  IsString,
  IsArray,
} from 'class-validator';
import { BaseDto } from '../../../common/base/base.dto';

export class CreateTicketDto {
  @ApiProperty({
    description: 'The name of the ticket',
    example: 'Fix login issue',
  })
  @IsString()
  @IsNotEmpty()
  name?: string;

  @ApiProperty({
    description:
      'The code of the ticket (auto-generated by backend if not provided)',
    example: 'TICKET-001',
    required: false,
  })
  @IsString()
  @IsOptional()
  code?: string;

  @ApiProperty({
    description: 'The description of the ticket',
    example: 'Users are unable to login to the system',
    required: false,
  })
  @IsString()
  @IsOptional()
  description?: string;

  @ApiProperty({
    description: 'The ID of the ticket space',
    example: 1,
  })
  @IsNumber()
  @IsNotEmpty()
  ticketSpaceId?: number;

  @ApiProperty({
    description: 'The name of the ticket space',
    example: 'IT Support',
    required: false,
  })
  @IsString()
  @IsOptional()
  ticketSpaceName?: string;

  @ApiProperty({
    description: 'The prefix of the ticket space',
    example: 'IT',
    required: false,
  })
  @IsString()
  @IsOptional()
  ticketSpacePrefix?: string;

  @ApiProperty({
    description: 'The ID of the division associated with the ticket space',
    example: 1,
    required: false,
  })
  @IsNumber()
  @IsOptional()
  ticketSpaceDivisionId?: number;

  @ApiProperty({
    description: 'The ID of the status',
    example: 1,
    required: false,
  })
  @IsNumber()
  @IsOptional()
  statusId?: number;

  @ApiProperty({
    description: 'The ID of the severity',
    example: 1,
    required: false,
  })
  @IsNumber()
  @IsOptional()
  severityId?: number;

  @ApiProperty({
    description: 'The ID of the ticket type',
    example: 1,
    required: false,
  })
  @IsNumber()
  @IsOptional()
  ticketTypeId?: number;

  @ApiProperty({
    description: 'The ID of the department',
    example: 1,
    required: false,
  })
  @IsNumber()
  @IsOptional()
  departmentId?: number;

  @ApiProperty({
    description: 'The ID of the ticket queue',
    example: 1,
    required: false,
  })
  @IsNumber()
  @IsOptional()
  queueId?: number;

  @ApiProperty({
    description: 'The ID of the impact',
    example: 1,
    required: false,
  })
  @IsNumber()
  @IsOptional()
  impactId?: number;

  @ApiProperty({
    description: 'The ID of the ticket SLA',
    example: 1,
    required: false,
  })
  @IsNumber()
  @IsOptional()
  ticketSlaId?: number;

  @ApiProperty({
    description: 'The ID of the assignee',
    example: 1,
    required: false,
  })
  @IsNumber()
  @IsOptional()
  assigneeId?: number;

  @ApiProperty({
    description: 'The planned effort in hours',
    example: 8.5,
    required: false,
  })
  @IsNumber()
  @IsOptional()
  plannedEffort?: number;

  @ApiProperty({
    description: 'The actual effort in hours',
    example: 10.0,
    required: false,
  })
  @IsNumber()
  @IsOptional()
  actualEffort?: number;

  @ApiProperty({
    description: 'The completion date of the ticket',
    example: '2024-12-31',
    required: false,
  })
  @IsString()
  @IsOptional()
  completionDate?: string;

  @ApiProperty({
    description:
      'Array of participant IDs (deprecated - use participants instead)',
    example: [1, 2, 3],
    type: [Number],
    required: false,
  })
  @IsArray()
  @IsOptional()
  participantIds?: number[];

  @ApiProperty({
    description:
      'Array of full participant objects (preferred over IDs for better performance)',
    example: [
      {
        id: 1,
        userId: 1,
        userFirstName: 'John',
        userLastName: 'Doe',
        userEmail: 'john@example.com',
        userProfilePicture: 'url',
      },
    ],
    type: 'array',
    required: false,
  })
  @IsArray()
  @IsOptional()
  participants?: any[];

  // Denormalized fields (read-only, returned in responses, but we'll accept them optionally)
  @IsString()
  @IsOptional()
  statusName?: string;

  @IsString()
  @IsOptional()
  statusColor?: string;

  @IsString()
  @IsOptional()
  statusBase?: string;

  @IsString()
  @IsOptional()
  severityName?: string;

  @IsString()
  @IsOptional()
  severityColor?: string;

  @IsString()
  @IsOptional()
  ticketTypeName?: string;

  @IsString()
  @IsOptional()
  ticketTypeIcon?: string;

  @IsString()
  @IsOptional()
  departmentName?: string;

  @IsString()
  @IsOptional()
  queueName?: string;

  @IsString()
  @IsOptional()
  impactName?: string;

  @IsNumber()
  @IsOptional()
  slaResponseTime?: number;

  @IsNumber()
  @IsOptional()
  slaResolutionTime?: number;

  @IsString()
  @IsOptional()
  assigneeName?: string;

  @IsString()
  @IsOptional()
  assigneeProfilePicUrl?: string;

  @IsString()
  @IsOptional()
  assigneeEmail?: string;

  @ApiProperty({ required: false })
  @IsOptional()
  status?: any;

  @ApiProperty({ required: false })
  @IsOptional()
  severity?: any;

  @ApiProperty({ required: false })
  @IsOptional()
  ticketType?: any;

  @ApiProperty({ required: false })
  @IsOptional()
  department?: any;

  @ApiProperty({ required: false })
  @IsOptional()
  queue?: any;

  @ApiProperty({ required: false })
  @IsOptional()
  impact?: any;

  @ApiProperty({ required: false })
  @IsOptional()
  ticketSla?: any;

  @ApiProperty({ required: false })
  @IsOptional()
  assignee?: any;
}

export class UpdateTicketDto {
  @ApiProperty({
    description: 'The ID of the ticket',
    example: 1,
  })
  @IsNumber()
  @IsNotEmpty()
  id: number;

  @ApiProperty({
    description: 'The name of the ticket',
    example: 'Fix login issue',
    required: false,
  })
  @IsString()
  @IsOptional()
  name?: string;

  @ApiProperty({
    description: 'The code of the ticket',
    example: 'TICKET-001',
    required: false,
  })
  @IsString()
  @IsOptional()
  code?: string;

  @ApiProperty({
    description: 'The description of the ticket',
    example: 'Users are unable to login to the system',
    required: false,
  })
  @IsString()
  @IsOptional()
  description?: string;

  @ApiProperty({
    description: 'The ID of the ticket space',
    example: 1,
    required: false,
  })
  @IsNumber()
  @IsOptional()
  ticketSpaceId?: number;

  @ApiProperty({
    description: 'The name of the ticket space',
    example: 'IT Support',
    required: false,
  })
  @IsString()
  @IsOptional()
  ticketSpaceName?: string;

  @ApiProperty({
    description: 'The prefix of the ticket space',
    example: 'IT',
    required: false,
  })
  @IsString()
  @IsOptional()
  ticketSpacePrefix?: string;

  @ApiProperty({
    description: 'The ID of the division associated with the ticket space',
    example: 1,
    required: false,
  })
  @IsNumber()
  @IsOptional()
  ticketSpaceDivisionId?: number;

  @ApiProperty({
    description: 'The ID of the status',
    example: 1,
    required: false,
  })
  @IsNumber()
  @IsOptional()
  statusId?: number;

  @ApiProperty({
    description: 'The ID of the severity',
    example: 1,
    required: false,
  })
  @IsNumber()
  @IsOptional()
  severityId?: number;

  @ApiProperty({
    description: 'The ID of the ticket type',
    example: 1,
    required: false,
  })
  @IsNumber()
  @IsOptional()
  ticketTypeId?: number;

  @ApiProperty({
    description: 'The ID of the department',
    example: 1,
    required: false,
  })
  @IsNumber()
  @IsOptional()
  departmentId?: number;

  @ApiProperty({
    description: 'The ID of the ticket queue',
    example: 1,
    required: false,
  })
  @IsNumber()
  @IsOptional()
  queueId?: number;

  @ApiProperty({
    description: 'The ID of the impact',
    example: 1,
    required: false,
  })
  @IsNumber()
  @IsOptional()
  impactId?: number;

  @ApiProperty({
    description: 'The ID of the ticket SLA',
    example: 1,
    required: false,
  })
  @IsNumber()
  @IsOptional()
  ticketSlaId?: number;

  @ApiProperty({
    description: 'The ID of the assignee',
    example: 1,
    required: false,
  })
  @IsNumber()
  @IsOptional()
  assigneeId?: number;

  @ApiProperty({
    description: 'The planned effort in hours',
    example: 8.5,
    required: false,
  })
  @IsNumber()
  @IsOptional()
  plannedEffort?: number;

  @ApiProperty({
    description: 'The actual effort in hours',
    example: 10.0,
    required: false,
  })
  @IsNumber()
  @IsOptional()
  actualEffort?: number;

  @ApiProperty({
    description: 'The completion date of the ticket',
    example: '2024-12-31',
    required: false,
  })
  @IsString()
  @IsOptional()
  completionDate?: string;

  @ApiProperty({
    description:
      'Array of participant IDs (deprecated - use participants instead)',
    example: [1, 2, 3],
    type: [Number],
    required: false,
  })
  @IsArray()
  @IsOptional()
  participantIds?: number[];

  @ApiProperty({
    description:
      'Array of full participant objects (preferred over IDs for better performance)',
    example: [
      {
        id: 1,
        userId: 1,
        userFirstName: 'John',
        userLastName: 'Doe',
        userEmail: 'john@example.com',
        userProfilePicture: 'url',
      },
    ],
    type: 'array',
    required: false,
  })
  @IsArray()
  @IsOptional()
  participants?: any[];

  // Denormalized fields (read-only, returned in responses, but we'll accept them optionally)
  @IsString()
  @IsOptional()
  statusName?: string;

  @IsString()
  @IsOptional()
  statusColor?: string;

  @IsString()
  @IsOptional()
  statusBase?: string;

  @IsString()
  @IsOptional()
  severityName?: string;

  @IsString()
  @IsOptional()
  severityColor?: string;

  @IsString()
  @IsOptional()
  ticketTypeName?: string;

  @IsString()
  @IsOptional()
  ticketTypeIcon?: string;

  @IsString()
  @IsOptional()
  departmentName?: string;

  @IsString()
  @IsOptional()
  queueName?: string;

  @IsString()
  @IsOptional()
  impactName?: string;

  @IsNumber()
  @IsOptional()
  slaResponseTime?: number;

  @IsNumber()
  @IsOptional()
  slaResolutionTime?: number;

  @IsString()
  @IsOptional()
  assigneeName?: string;

  @IsString()
  @IsOptional()
  assigneeProfilePicUrl?: string;

  @IsString()
  @IsOptional()
  assigneeEmail?: string;

  @ApiProperty({ required: false })
  @IsOptional()
  status?: any;

  @ApiProperty({ required: false })
  @IsOptional()
  severity?: any;

  @ApiProperty({ required: false })
  @IsOptional()
  ticketType?: any;

  @ApiProperty({ required: false })
  @IsOptional()
  department?: any;

  @ApiProperty({ required: false })
  @IsOptional()
  queue?: any;

  @ApiProperty({ required: false })
  @IsOptional()
  impact?: any;

  @ApiProperty({ required: false })
  @IsOptional()
  ticketSla?: any;

  @ApiProperty({ required: false })
  @IsOptional()
  assignee?: any;
}

export class ResponseTicketDto extends BaseDto {
  @ApiProperty({
    description: 'The name of the ticket',
    example: 'Fix login issue',
  })
  name: string;

  @ApiProperty({
    description: 'The code of the ticket',
    example: 'TICKET-001',
  })
  code: string;

  @ApiProperty({
    description: 'The description of the ticket',
    example: 'Users are unable to login to the system',
  })
  description: string;

  @ApiProperty({
    description: 'The ID of the ticket space',
    example: 1,
  })
  ticketSpaceId: number;

  @ApiProperty({
    description: 'The name of the ticket space',
    example: 'IT Support',
  })
  ticketSpaceName: string;

  @ApiProperty({
    description: 'The prefix of the ticket space',
    example: 'IT',
  })
  ticketSpacePrefix: string;

  @ApiProperty({
    description: 'The ID of the status',
    example: 1,
  })
  statusId: number;

  @ApiProperty({
    description: 'The name of the status',
    example: 'Open',
  })
  statusName: string;

  @ApiProperty({
    description: 'The color of the status',
    example: '#FF0000',
  })
  statusColor: string;

  @ApiProperty({
    description: 'The base of the status',
    example: 'open',
  })
  statusBase: string;

  @ApiProperty({
    description: 'The ID of the severity',
    example: 1,
  })
  severityId: number;

  @ApiProperty({
    description: 'The name of the severity',
    example: 'High',
  })
  severityName: string;

  @ApiProperty({
    description: 'The color of the severity',
    example: '#FF0000',
  })
  severityColor: string;

  @ApiProperty({
    description: 'The ID of the ticket type',
    example: 1,
  })
  ticketTypeId: number;

  @ApiProperty({
    description: 'The name of the ticket type',
    example: 'Bug',
  })
  ticketTypeName: string;

  @ApiProperty({
    description: 'The icon of the ticket type',
    example: 'bug_icon',
  })
  ticketTypeIcon: string;

  @ApiProperty({
    description: 'The ID of the department',
    example: 1,
  })
  departmentId: number;

  @ApiProperty({
    description: 'The name of the department',
    example: 'Engineering',
  })
  departmentName: string;

  @ApiProperty({
    description: 'The ID of the ticket queue',
    example: 1,
  })
  queueId: number;

  @ApiProperty({
    description: 'The name of the ticket queue',
    example: 'Support',
  })
  queueName: string;

  @ApiProperty({
    description: 'The ID of the impact',
    example: 1,
  })
  impactId: number;

  @ApiProperty({
    description: 'The name of the impact',
    example: 'High',
  })
  impactName: string;

  @ApiProperty({
    description: 'The response time for the SLA in minutes',
    example: 60,
  })
  slaResponseTime: number;

  @ApiProperty({
    description: 'The resolution time for the SLA in minutes',
    example: 240,
  })
  slaResolutionTime: number;

  @ApiProperty({
    description: 'The ID of the assignee',
    example: 1,
  })
  assigneeId: number;

  @ApiProperty({
    description: 'The name of the assignee',
    example: 'John Doe',
  })
  assigneeName: string;

  @ApiProperty({
    description: 'The profile pic URL of the assignee',
    example: 'https://example.com/pic.jpg',
  })
  assigneeProfilePicUrl: string;

  @ApiProperty({
    description: 'The email of the assignee',
    example: 'john.doe@example.com',
  })
  assigneeEmail: string;

  @ApiProperty({
    description: 'The planned effort in hours',
    example: 8.5,
  })
  plannedEffort: number;

  @ApiProperty({
    description: 'The actual effort in hours',
    example: 10.0,
  })
  actualEffort: number;

  @ApiProperty({
    description: 'The completion date of the ticket',
    example: '2024-12-31',
  })
  completionDate?: string;

  @ApiProperty({
    description: 'Ticket space details',
  })
  ticketSpace?: any;

  @ApiProperty({
    description: 'Status details',
  })
  status?: any;

  @ApiProperty({
    description: 'Severity details',
  })
  severity?: any;

  @ApiProperty({
    description: 'Ticket type details',
  })
  ticketType?: any;

  @ApiProperty({
    description: 'Department details',
  })
  department?: any;

  @ApiProperty({
    description: 'Queue details',
  })
  queue?: any;

  @ApiProperty({
    description: 'Impact details',
  })
  impact?: any;

  @ApiProperty({
    description: 'Assignee details',
  })
  assignee?: any;

  @ApiProperty({
    description: 'Participants',
    type: [Object],
  })
  participants?: any[];
}
